60 deploy shared as an npm package
AI-News-Team/AI-News pull request #119
Opened 2023-10-23 07:46 UTC by ArtemKech

# /shared deployed as NPM package!

Now [`ai-daily`](https://www.npmjs.com/package/ai-daily?activeTab=readme) is available on **_npm_** 

# Changes:

### Root:
* Added `.npmignore` file so I can just deploy `/shared`

### API & Client:
* Updated all imports with: `ai-daily`
* Added new package to `package.json`

### Shared & NPM page:
* Updated `README` file with code usage examples

# Usage:

Install with:
```shell
npm i ai-daily
```
And import like:
```typescript
import { Article } from '@ai-daily';
```
# Important note:
Please, let me know if you have an account with **_npm_** so I can add you guys as **collaborators**!

2023-10-26 00:16 UTC, AardhynLavender requested changes
Looks good, but... Can you make sure there are no duplicated types and functions between the `api` and `client`... I think there are some lying around the client app.

2023-10-26 00:16 UTC, AardhynLavender commented on shared/README.md
Can we replace this with `JSDoc` comments above each method and type. That way, our editors intellisense can display the documentation when we use the library.

2023-10-26 01:41 UTC, gpseal approved these changes
Great idea, didn't realise this could be done, adds an extra layer to the app, good job

2023-10-27 07:34 UTC, ArtemKech commented on shared/README.md
Yeah, this is a really good idea. I will add that and merge it

2023-10-27 08:39 UTC, merged