`39` semantic searching
AI-News-Team/AI-News pull request #41
Opened 2023-04-24 08:53 UTC by AardhynLavender

## Semantic Searching

Researching and implementing a prototype for semantic searching on articles

> The `Docker` environment takes a good **6-10 minutes** to build, and has issues communicating with the server running on the host machine. Nothing `Docker Compose` can't solve later...

> I'd recommend using the `init.local.sh` script instead to play around with this, it will install the modules it needs.

The program initially fetches all the articles in one category ( another reason why we need to be able to fetch **all** articles, albeit with pagination ) and reorders the articles based on the search term you type in.

use good old `ctrl+c` ( SIGTERM ) to exit the script.

# Todo

- [ ] Flask application to allow the server to communicate with the search engine
- [ ] Store tensor of article names ( and other fields maybe ) in the database on creation.
- [ ] Search caching?

2023-05-02 10:14 UTC, gpseal requested changes
Wow, a great addition to the app, really great work here. 
I had a go with a couple of queries, and it works really well.  Some results seem a little less related than others, but the first few seem to be spot on, I guess that's the nature of search.

Error handling is good as always, which is appreciated (was useful in testing)

Just a couple of minor things I have pointed out to fix, not sure if the first one is necessary, but take a look.

2023-05-04 01:57 UTC, AardhynLavender commented on server/template.env
> +SEARCH_ENGINE_PORT=
added 👍

2023-05-04 02:01 UTC, AardhynLavender commented on search/init.local.sh
> +pip install -r requirements.txt
I didn't have this problem on my machine... [seems to make sense though](https://pip.pypa.io/en/stable/cli/pip_install/#cmdoption-user).

2023-05-04 23:52 UTC, ArtemKech approved these changes
Works great! It is a really cool feature. Works better than most of the searches on other websites :). I agree with Greg, that some of the results are quite irrelevant to what you are trying to search but the first few seem to be accurate. Good job!

2023-05-07 19:56 UTC, merged