Finish the categories
AI-News-Team/AI-News pull request #53
Opened 2023-05-17 01:25 UTC by ArtemKech

# CHANGES:
### Fixed: **_BBC_** & **_CNN_** spiders
*  _**BBC**_ - added categories to the spider. It fetches them all now.
*  _**CNN**_ - added categories to the spider. Fixed some of the fields that were not retrieving data. Time is in `UTC` format

### Closed issues: 
* ( #44 )
* ( # 33 )
* ( #40 )

---
### **NOTE:** There is one new category called `US`. Do we want to keep it separate or should we add to `international`?

2023-05-18 01:20 UTC, AardhynLavender commented
@ArtemKech, Cant get scrappy to work from polytech today. I'll have a look this evening.

What categories are you using currently, I dont see the categories changed in the database.

2023-05-21 20:50 UTC, AardhynLavender requested changes
Looking good!

Getting some key constraint errors on `article.create`

2023-05-21 20:50 UTC, AardhynLavender commented on database/src/init.sql
> -        ('sport', 'generic sports articles');
looks good.

2023-05-21 20:50 UTC, AardhynLavender commented on scraper/newsscrapper/pipelines.py
> +            json.dump(articles, f, indent=4)
Probably don't need this left in.

2023-05-26 11:40 UTC, AardhynLavender requested changes
Looking good, so close!

Couple of quick ones...

- Bumping `name` and `author` up to **varchar(256)` seems a better limit for those fields.
- Some `publication_date`s are legitimately larger than 24 characters. `varchar(32)` fits all our current timestamp instances.

I've noticed *Fox News* still has a few categories left to sort out--such as *realestate*. All the others are working great though 😁.

2023-05-27 07:55 UTC, ArtemKech commented
@AardhynLavender. I made sure that the categories that are not in `db` not going to be scraped. Should work fine now

2023-05-27 09:32 UTC, AardhynLavender requested changes
Great stuff! 😎,

Can you make those quick alterations to the fields failing their length constraints.

Then its a thumbs up from me.

2023-05-29 01:22 UTC, AardhynLavender approved these changes
Thanks for that, 👍

2023-05-29 01:32 UTC, merged