Gseal 56 re writer module
AI-News-Team/AI-News pull request #65
Opened 2023-05-31 23:05 UTC by gpseal

Re writer module to reWrite scraped articles and load them to a new table

Scraped data will now go to a table called "Article_Raw", which will not be displayed on the front end.

Once the reWriter module is executed, it will pull all articles that have not already been re-written and paraphrase them one at a time, loading them to the original "Article" table after each article has been re-written.

Execute the module by entering the reWriter folder and entering "python reWriter.py"

2023-06-01 02:01 UTC, AardhynLavender requested changes
Nice. 

Just a few things thingsin the comments bellow.


#### Formatting

Can you make sure the formatter is being run in the `/api` directory.

```shell
npm run pretty
```

Or configure your IDE to format on save if that option is available.

2023-06-01 02:05 UTC, ArtemKech reviewed
@gpseal Just a small change to implement. Can you please add `{PORT}` variable on line 52 in `reWriter/reWriter.py` file. There is a variable for a port number inside `.env` file for that. 
But overall, really good job! I am glad that you have finally found a good paraphraser that actually works. I remember how painful that was to find a free model that does the job. 
Apply this change, and it will be ready for approval.

2023-06-07 00:42 UTC, gpseal commented on api/route/Article/article.create.ts
> +  const client = new Client({
Let me know if I haven't used this correctly

2023-06-07 02:17 UTC, gpseal commented on database/src/init.sql
>  -- Defaults --
I have implemented this, but it was causing a side effect with the article summary route query.  I have updated this to work, but I am not overly sure that it is functioning correctly, perhaps take a quick loo at it to make sure its all in order (I guess the fake category stuff is no longer relevant so will need to be removed anyway?)

2023-06-08 02:18 UTC, AardhynLavender approved these changes
Fantastic

2023-06-08 02:44 UTC, ArtemKech commented
Thanks for the applied changes as requested earlier. That looks better now! It's ready to go
<sub><sup>merry x-mas</sup></sub>

2023-06-08 02:45 UTC, ArtemKech approved these changes

2023-06-08 02:45 UTC, merged