chore(pipeline): make scrapy to send data individually
AI-News-Team/AI-News pull request #73
Opened 2023-07-24 00:59 UTC by ArtemKech

# Changes:
Just changed `pipelines.py` file. I got rid of the part where _Scrapy_ was sending an array of articles at the end of the spiders' scraping 
Also added name of the article to the terminal's output for error checking

2023-07-24 01:18 UTC, AardhynLavender requested changes
Looks like each call to `process_item` sends the accumulated articles rather than just the one being processed. 
Did this result in duplicated articles in your tests?

![image](https://github.com/AI-News-Team/AI-News/assets/83677410/b8e6f2fa-0cc8-4073-819a-a6300c7e62c6)

![image](https://github.com/AI-News-Team/AI-News/assets/83677410/9a7e42f4-1a5e-4df0-aa3e-0201f4ddb104)

![image](https://github.com/AI-News-Team/AI-News/assets/83677410/54b99f30-0176-489f-a747-2da014ee4326)

Should this be something like

```python
json_str: str = json.dumps(item, default=serialize_item)
article: dict = json.loads(json_str)
```

serialize just the acticl

2023-07-24 01:18 UTC, AardhynLavender commented on scraper/newsscrapper/pipelines.py
>          self.json.append(item)
is this member this still needed?

2023-07-24 02:18 UTC, gpseal approved these changes
Good simple solution, will allow more flexibility when posting scraped data, nice job.

2023-07-27 01:02 UTC, ArtemKech commented
My bad @AardhynLavender. Haven't noticed it doing this. I will fix that. Thanks for spotting this!

2023-07-27 02:23 UTC, AardhynLavender approved these changes
Epic

2023-07-27 02:49 UTC, glwatkins approved these changes
Fantastic, good additions to get the website functioning smoother.

2023-07-31 01:44 UTC, merged